version: "3"
services:
  api:
    image: yasiryounas/fastapi-app-1
    depends_on:
      - postgres
    ports:
      - 8000:8000
      # volumes:
      #   - ./:/usr/src/app:ro
      # command: uvicorn app.main:app --host 0.0.0.0 --post 8000 --reload
      #- <port on localhost>:>port on container>
      # env_file:
      #   - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=yasihome
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
